export default people = [
  {
    firstName: "Devlin",
    lastName: "Standring",
    email: "dstandring0@uwaterloo.ca",
    currentTerm: "2B",
    program: "Mathematics",
    timeLine: [
      {
        type: "study",
        term: "1A",
        termDescription: "Math 135, Math 137, CS 135, Phys 121, SPCOM 100",
        startDate: "Sept 2020",
        endDate: "Dec 2020",
      },
      {
        type: "study",
        term: "1B ",
        termDescription: "Math 136, Math 138, CS 136, AFM 101, Econ 101",
        startDate: "Jan 2021",
        endDate: "Apr 2021",
      },
      {
        type: "work",
        term: "Coop 1",
        termDescription: "Testing and QA @ ABC Inc.",
        startDate: "May 2021",
        endDate: "Aug 2021",
      },
      {
        type: "study",
        term: "2A",
        termDescription: "CS 245, CS 246, Math 239, Stat 230, AFM 102",
        startDate: "Sep 2021",
        endDate: "Dec 2021",
      },
      {
        type: "work",
        term: "Coop 2",
        termDescription: "Data Scientist @ DEF Inc.",
        startDate: "May 2022",
        endDate: "Aug 2022",
      },
      {
        type: "study",
        term: "2B",
        termDescription: "CS 241, CS 251, CS 240, SPCOM 200, Stat 231 ",
        startDate: "Sept 2022",
        endDate: "Dec 2022",
      },
    ],
    links: [
      {
        type: "LinkedIn",
        link: "https://www.linkedin.com",
      },
      {
        type: "Email",
        link: "mailto:email@gmail.com",
      },
      {
        type: "GitHub",
        link: "https://www.github.com",
      },
      {
        type: "Discord",
        link: "https://www.discord.com",
      },
    ],
  },
  {
    firstName: "Corny",
    lastName: "Winterbourne",
    email: "cwinterbourne1@uwaterloo.ca",
    currentTerm: "Coop 6",
    program: "Computer Science",
    timeLine: [
      {
        type: "study",
        term: "1A",
        termDescription: "Math 135, Math 137, CS 135, Phys 121, SPCOM 100",
        startDate: "Sept 2020",
        endDate: "Dec 2020",
      },
      {
        type: "study",
        term: "1B ",
        termDescription: "Math 136, Math 138, CS 136, AFM 101, Econ 101",
        startDate: "Jan 2021",
        endDate: "Apr 2021",
      },
      {
        type: "work",
        term: "Coop 1",
        termDescription: "Testing and QA @ ABC Inc.",
        startDate: "May 2021",
        endDate: "Aug 2021",
      },
      {
        type: "study",
        term: "2A",
        termDescription: "CS 245, CS 246, Math 239, Stat 230, AFM 102",
        startDate: "Sep 2021",
        endDate: "Dec 2021",
      },
      {
        type: "work",
        term: "Coop 2",
        termDescription: "Data Scientist @ DEF Inc.",
        startDate: "May 2022",
        endDate: "Aug 2022",
      },
      {
        type: "study",
        term: "2B",
        termDescription: "CS 241, CS 251, CS 240, SPCOM 200, Stat 231 ",
        startDate: "Sept 2022",
        endDate: "Dec 2022",
      },
      {
        type: "work",
        term: "Coop 3",
        termDescription: "Data Scientist @ GHI Inc.",
        startDate: "Jan 2023",
        endDate: "Apr 2022",
      },
      {
        type: "work",
        term: "Coop 4",
        termDescription: "Data Scientist @ DEF Inc.",
        startDate: "May 2023",
        endDate: "Aug 2023",
      },
      {
        type: "study",
        term: "3A",
        termDescription: "CS 341, CS 350, Phys 175, ENGL 210F",
        startDate: "Sept 2023",
        endDate: "Dec 2023",
      },
      {
        type: "work",
        term: "Coop 5",
        termDescription: "Data Scientist @ GHI Inc.",
        startDate: "Jan 2024",
        endDate: "Apr 2024",
      },
      {
        type: "work",
        term: "Coop 6",
        termDescription: "Data Scientist @ DEF Inc.",
        startDate: "May 2024",
        endDate: "Aug 2024",
      },
    ],
    links: [
      {
        type: "LinkedIn",
        link: "https://www.linkedin.com",
      },
      {
        type: "Email",
        link: "mailto:email@gmail.com",
      },
      {
        type: "GitHub",
        link: "https://www.github.com",
      },
      {
        type: "Discord",
        link: "https://www.discord.com",
      },
    ],
  },
  {
    firstName: "Noell",
    lastName: "Duckit",
    email: "nduckit2@uwaterloo.ca",
    currentTerm: "1B",
    program: "Computer Science",
    timeLine: [
      {
        type: "study",
        term: "1A",
        termDescription: "Math 135, Math 137, CS 135, Phys 121, SPCOM 100",
        startDate: "Sept 2020",
        endDate: "Dec 2020",
      },
      {
        type: "study",
        term: "1B ",
        termDescription: "Math 136, Math 138, CS 136, AFM 101, Econ 101",
        startDate: "Jan 2021",
        endDate: "Apr 2021",
      },
    ],
    links: [
      {
        type: "LinkedIn",
        link: "https://www.linkedin.com",
      },
      {
        type: "Email",
        link: "mailto:email@gmail.com",
      },
      {
        type: "GitHub",
        link: "https://www.github.com",
      },
      {
        type: "Discord",
        link: "https://www.discord.com",
      },
    ],
  },
  {
    firstName: "Barnett",
    lastName: "Lory",
    email: "blory3@uwaterloo.ca",
    currentTerm: "1A",
    program: "Mathematics",
    timeLine: [
      {
        type: "study",
        term: "1A",
        termDescription: "Math 135, Math 137, CS 135, Phys 121, SPCOM 100",
        startDate: "Sept 2020",
        endDate: "Dec 2020",
      },
    ],
    links: [
      {
        type: "LinkedIn",
        link: "https://www.linkedin.com",
      },
      {
        type: "Email",
        link: "mailto:email@gmail.com",
      },
      {
        type: "GitHub",
        link: "https://www.github.com",
      },
      {
        type: "Discord",
        link: "https://www.discord.com",
      },
    ],
  },
  {
    firstName: "Arlyn",
    lastName: "Chomley",
    email: "achomley4@uwaterloo.ca",
    currentTerm: "3A",
    program: "Mathematics",
    timeLine: [
      {
        type: "study",
        term: "1A",
        termDescription: "Math 135, Math 137, CS 135, Phys 121, SPCOM 100",
        startDate: "Sept 2020",
        endDate: "Dec 2020",
      },
      {
        type: "study",
        term: "1B ",
        termDescription: "Math 136, Math 138, CS 136, AFM 101, Econ 101",
        startDate: "Jan 2021",
        endDate: "Apr 2021",
      },
      {
        type: "study",
        term: "2A",
        termDescription: "CS 245, CS 246, Math 239, Stat 230, AFM 102",
        startDate: "Sep 2021",
        endDate: "Dec 2021",
      },
      {
        type: "study",
        term: "2B",
        termDescription: "CS 241, CS 251, CS 240, SPCOM 200, Stat 231 ",
        startDate: "Sept 2022",
        endDate: "Dec 2022",
      },
      {
        type: "study",
        term: "3A",
        termDescription: "CS 341, CS 350, Phys 175, ENGL 210F",
        startDate: "Sept 2023",
        endDate: "Dec 2023",
      },
    ],
    links: [
      {
        type: "LinkedIn",
        link: "https://www.linkedin.com",
      },
      {
        type: "Email",
        link: "mailto:email@gmail.com",
      },
      {
        type: "GitHub",
        link: "https://www.github.com",
      },
      {
        type: "Discord",
        link: "https://www.discord.com",
      },
    ],
  },
  {
    CurSemester: "Fall",
    currentTerm: "1B",
    program: "Biology",
    firstName: "Andrew",
    lastName: "Turner",
    startYear: 2022,
    student_id: 16134702,
    timeline: [
      {
        termDescription: "AFM 202, CS 136, CS 241",
        endDate: "Dec 2022",
        semester: "Fall",
        startDate: "Sept 2022",
        term: "1A",
        type: "study",
        year: 2022,
      },
      {
        termDescription: "ENGL 109, ERS 106, FR 151",
        endDate: "Dec 2022",
        semester: "Fall",
        startDate: "Sept 2022",
        term: "1B",
        type: "study",
        year: 2022,
      },
    ],
    email: "andrewturner@uwaterloo.ca",
    links: [
      {
        type: "LinkedIn",
        link: "https://www.linkedin.com",
      },
      {
        type: "Email",
        link: "mailto:email@gmail.com",
      },
      {
        type: "GitHub",
        link: "https://www.github.com",
      },
      {
        type: "Discord",
        link: "https://www.discord.com",
      },
    ],
  },
  {
    CurSemester: "Fall",
    currentTerm: "1B",
    program: "Mechanical Engineering",
    firstName: "Joshua",
    lastName: "Cooper",
    startYear: 2022,
    student_id: 15702380,
    timeline: [
      {
        termDescription: "Web Developer @ Alibaba Group",
        endDate: "Dec 2021",
        semester: "Fall",
        startDate: "Sept 2021",
        term: "Coop 1",
        type: "work",
        year: 2021,
      },
      {
        termDescription: "AFM 202, CS 136, CS 241",
        endDate: "Dec 2022",
        semester: "Fall",
        startDate: "Sept 2022",
        term: "1A",
        type: "study",
        year: 2022,
      },
      {
        termDescription: "ENGL 109, ERS 106, FR 151",
        endDate: "Dec 2022",
        semester: "Fall",
        startDate: "Sept 2022",
        term: "1B",
        type: "study",
        year: 2022,
      },
    ],
    email: "joshcoop@uwaterloo.ca",
    links: [
      {
        type: "LinkedIn",
        link: "https://www.linkedin.com",
      },
      {
        type: "Email",
        link: "mailto:email@gmail.com",
      },
      {
        type: "GitHub",
        link: "https://www.github.com",
      },
      {
        type: "Discord",
        link: "https://www.discord.com",
      },
    ],
  },
  {
    CurSemester: "Fall",
    currentTerm: "3A",
    program: "CS",
    firstName: "Emily",
    lastName: "Smith",
    startYear: 2020,
    student_id: 13336678,
    timeline: [
      {
        termDescription: "CS 136, EARTH 122, MATH 137",
        endDate: "Dec 2020",
        semester: "Fall",
        startDate: "Sept 2020",
        term: "1A",
        type: "study",
        year: 2020,
      },
      {
        termDescription: "HIST 208",
        endDate: "Dec 2020",
        semester: "Fall",
        startDate: "Sept 2020",
        term: "1B",
        type: "study",
        year: 2020,
      },
      {
        termDescription: "MATH 135",
        endDate: "Dec 2020",
        semester: "Fall",
        startDate: "Sept 2020",
        term: "2B",
        type: "study",
        year: 2020,
      },
      {
        termDescription: "MATH 145",
        endDate: "Dec 2020",
        semester: "Fall",
        startDate: "Sept 2020",
        term: "2A",
        type: "study",
        year: 2020,
      },
      {
        termDescription: "PHIL 145",
        endDate: "Dec 2020",
        semester: "Fall",
        startDate: "Sept 2020",
        term: "3A",
        type: "study",
        year: 2020,
      },
    ],
    email: "emilysmith@uwaterloo.ca",
    links: [
      {
        type: "LinkedIn",
        link: "https://www.linkedin.com",
      },
      {
        type: "Email",
        link: "mailto:email@gmail.com",
      },
      {
        type: "GitHub",
        link: "https://www.github.com",
      },
      {
        type: "Discord",
        link: "https://www.discord.com",
      },
    ],
  },
];
